# Create filebeat on each node
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: beat-__VERSION__
  namespace: logging
spec:
  type: filebeat
  version: 8.9.0
  # elasticsearchRef:
  #   name: elasticsearch
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
    output.logstash:
      hosts: ["logstash-ls-beats:5044"]  
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet # Les pods configurés comme ça doivent avoir ClusterFirstWithHostNet comme DnsPolicy
        hostNetwork: true # HostNetwork allows a pod to use the node network namespace. Doing so gives the pod access to any service running on localhost of the host.
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers # Volume to be mounted from containers to grab their logs
        - name: varlogpods
          hostPath:
            path: /var/log/pods # Volume to be mounted from pods to take pods logs
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers # Volume to be mounted from container to get docker storage volume logs