apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-__VERSION__
  namespace: logging
spec:
  version: 8.9.0
  # By default elasticsearch create a persistant volume to prevent the deletion of data in case the cluster of es is deleted accidently
  volumeClaimDeletePolicy: DeleteOnScaledownAndClusterDeletion # Delete this persistant volume when scale down or the cluster is deleted(when the cluster is deleted?)
  nodeSets:
  - name: elasticsearch
    count: 1
    config:
      node.store.allow_mmap: false
    # Volume claim configuration: persistant volume of 1Gi resource request
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce # Read write by a single node.
        resources:
          requests:
            storage: 200Mi
        storageClassName: standard  