apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-__VERSION__
  namespace: logging
spec:
  version: 8.9.0
  volumeClaimDeletePolicy: DeleteOnScaledownAndClusterDeletion # Delete this persistant volume when scale down or the cluster is deleted
  nodeSets:
  - name: elasticsearch-__VERSION__
    count: 1
    config:
      node.store.allow_mmap: false
    # Volume claim configuration: persistant volume of 1Gi resource request
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data-__VERSION__ # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi
        storageClassName: standard  